import React from 'react'

export default function PrivacyPolicy() {
  return (
    <section className="min-h-screen flex flex-col justify-center items-center px-4">
        <h1 className='text-center text-black py-12 text-[30px] pb-10'>Privacy Policy</h1>
        <p className='text-start leading-7 mx-auto max-w-[1200px] w-full text-sm py-10'>Strikethrough asset auto invite thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main. Strikethrough asset auto invite thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main. Strikethrough asset auto invite thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main. Strikethrough asset auto invite
thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main. Strikethrough asset auto invite thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main. Strikethrough asset auto invite thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main. Strikethrough asset auto invite thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main. Strikethrough asset auto invite thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main. Strikethrough asset auto invite thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main. Strikethrough asset 
auto invite thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main. Strikethrough asset auto invite thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main. Strikethrough asset auto invite thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main.
Strikethrough asset auto invite thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main. Strikethrough asset auto invite thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main. Strikethrough asset auto invite thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main. Strikethrough asset auto invite
thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main. Strikethrough asset auto invite thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main. Strikethrough asset auto invite thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main. Strikethrough asset auto invite thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main. Strikethrough asset auto invite thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main. Strikethrough asset auto invite thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main. Strikethrough asset 
auto invite thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main. Strikethrough asset auto invite thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main. Strikethrough asset auto invite thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main.
Strikethrough asset auto invite thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main. Strikethrough asset auto invite thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main. Strikethrough asset auto invite thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main. Strikethrough asset auto invite
thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main. Strikethrough asset auto invite thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main. Strikethrough asset auto invite thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main. Strikethrough asset auto invite thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main. Strikethrough asset auto invite thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main. Strikethrough asset auto invite thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main. Strikethrough asset 
auto invite thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main. Strikethrough asset auto invite thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main. Strikethrough asset auto invite thumbnail connection bullet connection draft. Style text figjam subtract link share line component link main.</p>
    </section>
  )
}
